import "server-only";

import { isRecord } from "@/lib/lecture-source-metadata";
import {
  extractWebpageImages,
  storeDocumentImagesAsNoteMedia,
} from "@/lib/document-image-extraction";
import { LectureNoLongerExistsError } from "@/lib/lecture-processing-errors";
import { fetchYoutubeTranscriptSource } from "@/lib/youtube-transcript";
import { parseYoutubeVideoId } from "@/lib/youtube-url";
import {
  fetchReadableWebpage,
  prepareLectureFromTextSource,
} from "@/lib/manual-lectures";
import { createSupabaseServiceRoleClient } from "@/lib/supabase/server";

export type StoredLinkProcessingResult = {
  needsNotesGeneration: boolean;
};

function parsePendingLinkUrl(value: unknown) {
  return typeof value === "string" && value.trim().length > 0 ? value.trim() : null;
}

export async function processStoredLinkLecture(params: {
  lectureId: string;
}): Promise<StoredLinkProcessingResult> {
  const supabase = createSupabaseServiceRoleClient();
  const { data: lecture, error: lectureError } = await supabase
    .from("lectures")
    .select("id, user_id, language_hint, processing_metadata")
    .eq("id", params.lectureId)
    .maybeSingle();

  if (lectureError) {
    throw lectureError;
  }

  // The learner deleted the lecture while this stage was still queued behind it. `.single()` used
  // to report that as PostgREST's "Cannot coerce the result to a single JSON object", which said
  // nothing about what had happened and reached Sentry as an unexplained defect.
  if (!lecture) {
    throw new LectureNoLongerExistsError(params.lectureId);
  }

  const lectureRow = lecture as {
    id: string;
    user_id: string;
    language_hint: string | null;
    processing_metadata: unknown;
  };
  const metadata = isRecord(lectureRow.processing_metadata)
    ? lectureRow.processing_metadata
    : {};
  const pendingLinkUrl = parsePendingLinkUrl(metadata.pendingLinkUrl);

  if (!pendingLinkUrl) {
    throw new Error("Ni povezave za obdelavo.");
  }

  const { error: statusError } = await supabase
    .from("lectures")
    .update(
      {
        status: "queued",
        error_message: null,
        processing_metadata: {
          ...metadata,
          processing: {
            stage: "reading_link",
            updatedAt: new Date().toISOString(),
            errorMessage: null,
          },
        },
      } as never,
    )
    .eq("id", lectureRow.id)
    .eq("user_id", lectureRow.user_id);

  if (statusError) {
    throw new Error(statusError.message);
  }

  const youtubeVideoId = parseYoutubeVideoId(pendingLinkUrl);

  if (youtubeVideoId) {
    const transcript = await fetchYoutubeTranscriptSource({
      videoId: youtubeVideoId,
      languageHint: lectureRow.language_hint,
    });

    await prepareLectureFromTextSource({
      lectureId: lectureRow.id,
      userId: lectureRow.user_id,
      sourceType: "link",
      text: transcript.text,
      blocks: transcript.blocks,
      titleHint: transcript.title ?? undefined,
      languageHint: lectureRow.language_hint ?? "sl",
      modelMetadata: {
        importMode: "link",
        linkKind: "youtube",
        sourceUrl: pendingLinkUrl,
        youtubeVideoId,
        captionLanguage: transcript.trackLanguage,
        captionAutoGenerated: transcript.isAutoGenerated,
      },
    });

    return { needsNotesGeneration: true };
  }

  const webpage = await fetchReadableWebpage({
    url: pendingLinkUrl,
  });
  const extractedImages = await extractWebpageImages({
    html: webpage.html,
    pageUrl: webpage.finalUrl,
    pageTitle: webpage.title,
  });
  const documentImages = await storeDocumentImagesAsNoteMedia({
    lectureId: lectureRow.id,
    userId: lectureRow.user_id,
    images: extractedImages,
  });

  await prepareLectureFromTextSource({
    lectureId: lectureRow.id,
    userId: lectureRow.user_id,
    sourceType: "link",
    text: webpage.text,
    titleHint: webpage.title,
    languageHint: lectureRow.language_hint ?? "sl",
    modelMetadata: {
      importMode: "link",
      sourceUrl: pendingLinkUrl,
      documentImages,
    },
  });

  return { needsNotesGeneration: true };
}
