// Retry policy for read-aloud chunk requests.
//
// A chunk is generated by whichever request wins the quota reservation; everyone else waits on
// that generation server-side and, if it is still running when their wait expires, is told to come
// back. That answer is a "not ready yet", not a failure — the work is still in flight — so the only
// correct response is to ask again. Nothing did, so it surfaced as an error and the reader had to
// press play again by hand.
//
// Kept separate from the component so the policy can be tested without a DOM.

export const TTS_CHUNK_PENDING_CODES = ["tts_generation_pending", "tts_provider_rate_limited"];

// Generation runs to roughly 100s, and each server-side wait absorbs ~24s of that before
// answering, so this budget covers a full generation with room for the tail.
export const TTS_CHUNK_PENDING_RETRY_BUDGET_MS = 150_000;

export type TtsChunkFailure = {
  code?: string;
  status: number;
};

// 429 is grouped with the pending codes because the route answers that way when the upstream voice
// provider is rate limiting us, which clears on its own exactly like a pending generation does.
export function isTtsChunkPendingFailure(failure: TtsChunkFailure | null | undefined) {
  if (!failure) {
    return false;
  }

  return TTS_CHUNK_PENDING_CODES.includes(failure.code ?? "") || failure.status === 429;
}

// The rate-limited variant answers immediately rather than after a server-side wait, so back off
// progressively instead of re-asking in a tight loop.
export function getTtsChunkRetryDelayMs(attempt: number) {
  return Math.min(2_000 * (attempt + 1), 8_000);
}

export function shouldRetryTtsChunkRequest(params: {
  failure: TtsChunkFailure | null | undefined;
  elapsedMs: number;
  // Playback resets bump a request id; once it moves, nobody is waiting on this chunk any more.
  cancelled: boolean;
}) {
  if (params.cancelled || !isTtsChunkPendingFailure(params.failure)) {
    return false;
  }

  return params.elapsedMs < TTS_CHUNK_PENDING_RETRY_BUDGET_MS;
}

// The daily-allowance slice of the read-aloud status the client keeps for the note being read.
export type TtsCreationQuota = {
  remainingSeconds: number;
  hasUnlimitedUsage?: boolean;
} | null;

// Asking for a chunk the remaining allowance cannot pay for always comes back "daily limit
// reached", so the prefetcher checks this before queueing rather than learning it from a 403.
export function canCreateTtsChunk(params: {
  quota: TtsCreationQuota;
  estimatedSeconds: number;
}) {
  if (!params.quota || params.quota.hasUnlimitedUsage) {
    return true;
  }

  return params.quota.remainingSeconds >= Math.max(1, Math.ceil(params.estimatedSeconds));
}

// Writing "the allowance is spent" into status has to be idempotent. React only skips a re-render
// when the next state is the *same object*, and the prefetch effect is rebuilt whenever the status
// object's identity changes. Handing back a fresh `{...current, remainingSeconds: 0}` for every
// rejected request therefore re-armed that effect, which sent another request, which produced
// another fresh object: in production this re-asked the chunk route roughly every 2.7s for as long
// as the reader left the note open, hundreds of 403s per session.
export function applyTtsCreationQuotaExhausted<T extends { remainingSeconds: number }>(
  current: T | null | undefined,
): T | null {
  if (!current) {
    return current ?? null;
  }

  if (current.remainingSeconds <= 0) {
    return current;
  }

  return { ...current, remainingSeconds: 0 };
}
