// Retry policy for read-aloud chunk requests.
//
// A chunk is generated by whichever request wins the quota reservation; everyone else waits on
// that generation server-side and, if it is still running when their wait expires, is told to come
// back. That answer is a "not ready yet", not a failure — the work is still in flight — so the only
// correct response is to ask again. Nothing did, so it surfaced as an error and the reader had to
// press play again by hand.
//
// Kept separate from the component so the policy can be tested without a DOM.

export const TTS_CHUNK_PENDING_CODES = ["tts_generation_pending", "tts_provider_rate_limited"];

// Generation runs to roughly 100s, and each server-side wait absorbs ~24s of that before
// answering, so this budget covers a full generation with room for the tail.
export const TTS_CHUNK_PENDING_RETRY_BUDGET_MS = 150_000;

export type TtsChunkFailure = {
  code?: string;
  status: number;
};

// 429 is grouped with the pending codes because the route answers that way when the upstream voice
// provider is rate limiting us, which clears on its own exactly like a pending generation does.
export function isTtsChunkPendingFailure(failure: TtsChunkFailure | null | undefined) {
  if (!failure) {
    return false;
  }

  return TTS_CHUNK_PENDING_CODES.includes(failure.code ?? "") || failure.status === 429;
}

// The rate-limited variant answers immediately rather than after a server-side wait, so back off
// progressively instead of re-asking in a tight loop.
export function getTtsChunkRetryDelayMs(attempt: number) {
  return Math.min(2_000 * (attempt + 1), 8_000);
}

export function shouldRetryTtsChunkRequest(params: {
  failure: TtsChunkFailure | null | undefined;
  elapsedMs: number;
  // Playback resets bump a request id; once it moves, nobody is waiting on this chunk any more.
  cancelled: boolean;
}) {
  if (params.cancelled || !isTtsChunkPendingFailure(params.failure)) {
    return false;
  }

  return params.elapsedMs < TTS_CHUNK_PENDING_RETRY_BUDGET_MS;
}
