import "server-only";

import type { StructuredSourceBlock } from "@/lib/text-source-processing";
import { expectedInputFailure } from "@/lib/lecture-failure-text";

const PLAYER_TIMEOUT_MS = 15_000;
const CAPTION_FETCH_TIMEOUT_MS = 15_000;

/*
 * The three ways a YouTube import fails are raised by code — `youtube_no_captions`,
 * `link_not_loadable` and `youtube_request_blocked` — and their wording lives in the message
 * catalogues, one per language, resolved where the failed note is read.
 *
 * `youtube_request_blocked` is its own code rather than being folded into "could not load":
 * a datacenter IP is refused by YouTube's bot wall no matter which client asks, so telling the
 * learner to check whether their video is public sends them to fix something that is not broken.
 */

type CaptionTrack = {
  baseUrl: string;
  languageCode: string;
  kind?: string;
};

export type YoutubeTranscriptSource = {
  videoId: string;
  title: string | null;
  text: string;
  blocks: StructuredSourceBlock[];
  trackLanguage: string;
  isAutoGenerated: boolean;
};

async function fetchWithTimeout(url: string, init: RequestInit, timeoutMs: number) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timeout);
  }
}

/**
 * The captionTracks embedded in the public watch page stopped being fetchable in 2024: their
 * timedtext URLs answer 200 with an empty body unless the request carries a proof-of-origin
 * token only the real player can mint. The innertube player endpoint queried as the ANDROID or
 * IOS client still returns caption URLs that serve actual content — verified live 2026-08-22
 * (ANDROID and IOS both worked; the web and TV clients did not).
 */
const INNERTUBE_CLIENTS = [
  {
    name: "ANDROID",
    userAgent: "com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip",
    context: {
      client: {
        clientName: "ANDROID",
        clientVersion: "20.10.38",
        androidSdkVersion: 30,
        hl: "en",
      },
    },
  },
  {
    name: "IOS",
    userAgent: "com.google.ios.youtube/20.10.4 (iPhone16,2; U; CPU iOS 17_5 like Mac OS X)",
    context: {
      client: {
        clientName: "IOS",
        clientVersion: "20.10.4",
        deviceModel: "iPhone16,2",
        hl: "en",
      },
    },
  },
] as const;

type PlayerResponse = {
  playabilityStatus?: { status?: string; reason?: string };
  videoDetails?: { title?: string };
  captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrack[] } };
};

/**
 * LOGIN_REQUIRED is YouTube's bot wall, not a permissions problem: measured from Vercel iad1 on
 * 2026-08-23, every innertube client answers LOGIN_REQUIRED / "Sign in to confirm you're not a
 * bot" while the identical calls from a residential IP return OK with caption tracks. The two
 * causes need different words, so the handshake reports which one it hit.
 */
type PlayerHandshake = { response: PlayerResponse } | { blocked: true } | null;

async function fetchPlayerResponse(videoId: string): Promise<PlayerHandshake> {
  let blocked = false;

  for (const client of INNERTUBE_CLIENTS) {
    try {
      const response = await fetchWithTimeout(
        "https://www.youtube.com/youtubei/v1/player?prettyPrint=false",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "User-Agent": client.userAgent,
          },
          body: JSON.stringify({ context: client.context, videoId }),
        },
        PLAYER_TIMEOUT_MS,
      );

      if (!response.ok) {
        continue;
      }

      const playerResponse = (await response.json()) as PlayerResponse;

      if (playerResponse.playabilityStatus?.status === "OK") {
        return { response: playerResponse };
      }

      if (playerResponse.playabilityStatus?.status === "LOGIN_REQUIRED") {
        blocked = true;
      }
    } catch {
      // The next client is the retry.
    }
  }

  return blocked ? { blocked: true } : null;
}

/**
 * Prefers a human-made track in the requested language, then auto-generated in that language,
 * then the same ladder for English, then whatever exists. Auto-generated captions are accepted
 * everywhere: for lecture recordings they are usually the only track there is.
 */
export function pickCaptionTrack(tracks: CaptionTrack[], languageHint: string | null) {
  if (tracks.length === 0) {
    return null;
  }

  const wanted = (languageHint ?? "").slice(0, 2).toLowerCase();
  const matches = (track: CaptionTrack, language: string, manual: boolean) =>
    track.languageCode?.toLowerCase().startsWith(language) &&
    (manual ? track.kind !== "asr" : true);

  for (const [language, manual] of [
    [wanted, true],
    [wanted, false],
    ["en", true],
    ["en", false],
  ] as Array<[string, boolean]>) {
    if (!language) {
      continue;
    }

    const track = tracks.find((candidate) => matches(candidate, language, manual));

    if (track) {
      return track;
    }
  }

  return tracks.find((track) => track.kind !== "asr") ?? tracks[0];
}

type Json3Event = {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Array<{ utf8?: string }>;
};

function decodeXmlEntities(value: string) {
  return value
    .replace(/&#(\d+);/g, (_match, code: string) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-f]+);/gi, (_match, code: string) => String.fromCodePoint(parseInt(code, 16)))
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'");
}

/**
 * The innertube caption URLs pin their own fmt parameter, so what actually arrives is timedtext
 * XML (`<p t="4220" d="1180">text</p>`), not json3 — an appended fmt=json3 loses to the one
 * already in the URL. Both shapes are handled; XML is what the ANDROID client serves today.
 */
function decodeCaptionEvents(payload: string): Json3Event[] {
  const trimmed = payload.trimStart();

  if (trimmed.startsWith("{")) {
    try {
      const parsed = JSON.parse(trimmed) as { events?: Json3Event[] };

      return parsed.events ?? [];
    } catch {
      return [];
    }
  }

  const events: Json3Event[] = [];
  const paragraphPattern = /<p\s+t="(\d+)"(?:\s+d="(\d+)")?[^>]*>([\s\S]*?)<\/p>/g;

  for (const match of trimmed.matchAll(paragraphPattern)) {
    const text = decodeXmlEntities(match[3].replace(/<[^>]+>/g, " ")).trim();

    if (!text) {
      continue;
    }

    events.push({
      tStartMs: Number(match[1]),
      dDurationMs: match[2] ? Number(match[2]) : undefined,
      segs: [{ utf8: text }],
    });
  }

  return events;
}

function formatTimestamp(ms: number) {
  const totalSeconds = Math.floor(ms / 1000);
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;

  return `${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;
}

const CAPTION_BLOCK_TARGET_CHARS = 700;

/** Groups caption lines into ~paragraph-sized blocks labelled with their start timestamp. */
export function buildCaptionBlocks(events: Json3Event[]): StructuredSourceBlock[] {
  const blocks: StructuredSourceBlock[] = [];
  let currentText: string[] = [];
  let currentStartMs = 0;

  const flush = () => {
    const text = currentText.join(" ").replace(/\s+/g, " ").trim();

    if (text.length > 0) {
      blocks.push({
        label: formatTimestamp(currentStartMs),
        pageNumber: null,
        text,
      });
    }

    currentText = [];
  };

  for (const event of events) {
    const text = (event.segs ?? [])
      .map((seg) => seg.utf8 ?? "")
      .join("")
      .replace(/\n/g, " ")
      .trim();

    if (!text) {
      continue;
    }

    if (currentText.length === 0) {
      currentStartMs = event.tStartMs ?? 0;
    }

    currentText.push(text);

    if (currentText.join(" ").length >= CAPTION_BLOCK_TARGET_CHARS) {
      flush();
    }
  }

  flush();

  return blocks;
}

export async function fetchYoutubeTranscriptSource(params: {
  videoId: string;
  languageHint?: string | null;
}): Promise<YoutubeTranscriptSource> {
  const handshake = await fetchPlayerResponse(params.videoId);

  if (!handshake) {
    throw expectedInputFailure("link_not_loadable");
  }

  if ("blocked" in handshake) {
    throw expectedInputFailure("youtube_request_blocked");
  }

  const tracks =
    handshake.response.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  const track = pickCaptionTrack(tracks, params.languageHint ?? null);

  if (!track?.baseUrl) {
    throw expectedInputFailure("youtube_no_captions");
  }

  const captionUrl = track.baseUrl;
  let captionResponse: Response;

  try {
    captionResponse = await fetchWithTimeout(
      captionUrl,
      { headers: { "User-Agent": INNERTUBE_CLIENTS[0].userAgent } },
      CAPTION_FETCH_TIMEOUT_MS,
    );
  } catch {
    throw expectedInputFailure("link_not_loadable");
  }

  if (!captionResponse.ok) {
    throw expectedInputFailure("link_not_loadable");
  }

  const events = decodeCaptionEvents(await captionResponse.text());
  const blocks = buildCaptionBlocks(events);
  const text = blocks.map((block) => block.text).join("\n\n");

  if (text.length < 200) {
    throw expectedInputFailure("youtube_no_captions");
  }

  return {
    videoId: params.videoId,
    title: handshake.response.videoDetails?.title?.trim() || null,
    text,
    blocks,
    trackLanguage: track.languageCode ?? "unknown",
    isAutoGenerated: track.kind === "asr",
  };
}
