-- The podcast player no longer shows captions, so the timings behind them feed nothing.
--
-- 0045 stays in the history rather than being deleted: it is recorded on production, and a remote
-- version with no local file blocks every later migration. Nothing reads this column. It was
-- derived from audio that is still cached, so if captions ever return it is regenerated by
-- re-synthesising rather than lost.
alter table public.lecture_podcast_segments
  drop column if exists word_timings;
